import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = process.cwd();

async function walk(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) return walk(absolute);
      return [absolute];
    }),
  );
  return files.flat();
}

function relative(file: string): string {
  return path.relative(ROOT, file).split(path.sep).join("/");
}

describe("backend test inventory", () => {
  it("lists every current API route and its exported HTTP method", async () => {
    const routeFiles = (await walk(path.join(ROOT, "app", "api")))
      .filter((file) => file.endsWith(`${path.sep}route.ts`))
      .map(relative)
      .sort();

    expect(routeFiles).toEqual([
      "app/api/account-content/route.ts",
      "app/api/admin/accounts/[wallet]/route.ts",
      "app/api/admin/accounts/route.ts",
      "app/api/admin/challenge/route.ts",
      "app/api/admin/client-errors/actions/route.ts",
      "app/api/admin/client-errors/route.ts",
      "app/api/admin/health/pipeline/route.ts",
      "app/api/admin/health/route.ts",
      "app/api/admin/login/route.ts",
      "app/api/admin/logout/route.ts",
      "app/api/admin/operations/fixed-costs/route.ts",
      "app/api/admin/operations/route.ts",
      "app/api/admin/outreach/actions/route.ts",
      "app/api/admin/outreach/route.ts",
      "app/api/admin/pages/actions/route.ts",
      "app/api/admin/pages/route.ts",
      "app/api/admin/published-sites/route.ts",
      "app/api/admin/social-project-slots/actions/route.ts",
      "app/api/admin/street-team/route.ts",
      "app/api/admin/subscribers/route.ts",
      "app/api/admin/support/actions/route.ts",
      "app/api/admin/support/route.ts",
      "app/api/admin/test-access/route.ts",
      "app/api/admin/token-launches/route.ts",
      "app/api/client-errors/route.ts",
      "app/api/cron/outreach/route.ts",
      "app/api/cron/social-posting/route.ts",
      "app/api/cron/subscription-lifecycle/route.ts",
      "app/api/dexscreener-pair/route.ts",
      "app/api/generate-free-site/route.ts",
      "app/api/generate-site-page/challenge/route.ts",
      "app/api/generate-site-page/route.ts",
      "app/api/generate-site-style/route.ts",
      "app/api/generation-status/route.ts",
      "app/api/health/route.ts",
      "app/api/hoodchat/challenge/route.ts",
      "app/api/hoodchat/messages/route.ts",
      "app/api/hoodchat/report/route.ts",
      "app/api/plan-payments/preflight/route.ts",
      "app/api/plan-payments/quote/route.ts",
      "app/api/plan-payments/verify/route.ts",
      "app/api/publish/challenge/route.ts",
      "app/api/publish/route.ts",
      "app/api/publish/visibility/route.ts",
      "app/api/social/challenge/route.ts",
      "app/api/social/connections/route.ts",
      "app/api/social/draft/route.ts",
      "app/api/social/mascot/image/route.ts",
      "app/api/social/mascot/visual-dna/route.ts",
      "app/api/social/posts/cancel/route.ts",
      "app/api/social/posts/reschedule/route.ts",
      "app/api/social/posts/route.ts",
      "app/api/social/project-slots/release/route.ts",
      "app/api/social/project-slots/route.ts",
      "app/api/social/telegram/connect/route.ts",
      "app/api/social/telegram/disconnect/route.ts",
      "app/api/social/telegram/route.ts",
      "app/api/social/telegram/status/route.ts",
      "app/api/social/voice-profile/route.ts",
      "app/api/social/voice-sample/route.ts",
      "app/api/social/x/connect/callback/route.ts",
      "app/api/social/x/connect/start/route.ts",
      "app/api/social/x/disconnect/route.ts",
      "app/api/street-team/interest/route.ts",
      "app/api/subscriptions/status/route.ts",
      "app/api/support/challenge/route.ts",
      "app/api/support/tickets/[id]/close/route.ts",
      "app/api/support/tickets/[id]/reply/route.ts",
      "app/api/support/tickets/anonymous/route.ts",
      "app/api/support/tickets/reference/route.ts",
      "app/api/support/tickets/route.ts",
      "app/api/telegram/subscription-webhook/route.ts",
      "app/api/token-chat/challenge/route.ts",
      "app/api/token-chat/messages/route.ts",
      "app/api/token-chat/report/route.ts",
      "app/api/token-holder-stats/route.ts",
      "app/api/token-launches/challenge/route.ts",
      "app/api/token-launches/route.ts",
      "app/api/token-trades/route.ts",
      "app/api/trending-robinhood/route.ts",
    ]);

    const methods = await Promise.all(
      routeFiles.map(async (file) => {
        const source = await readFile(path.join(ROOT, file), "utf8");
        const exported = [...source.matchAll(/export async function (GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\b/g)]
          .map((match) => match[1])
          .sort();
        return [file, exported] as const;
      }),
    );

    expect(Object.fromEntries(methods)).toEqual({
      "app/api/account-content/route.ts": ["GET"],
      "app/api/admin/accounts/[wallet]/route.ts": ["GET"],
      "app/api/admin/accounts/route.ts": ["GET"],
      "app/api/admin/challenge/route.ts": ["POST"],
      "app/api/admin/client-errors/actions/route.ts": ["POST"],
      "app/api/admin/client-errors/route.ts": ["GET"],
      "app/api/admin/health/pipeline/route.ts": ["GET"],
      "app/api/admin/health/route.ts": ["GET"],
      "app/api/admin/login/route.ts": ["POST"],
      "app/api/admin/logout/route.ts": ["POST"],
      "app/api/admin/operations/fixed-costs/route.ts": ["DELETE", "PATCH", "POST"],
      "app/api/admin/operations/route.ts": ["GET", "PATCH"],
      "app/api/admin/outreach/actions/route.ts": ["POST"],
      "app/api/admin/outreach/route.ts": ["GET"],
      "app/api/admin/pages/actions/route.ts": ["POST"],
      "app/api/admin/pages/route.ts": ["GET", "PATCH"],
      "app/api/admin/published-sites/route.ts": ["GET", "PATCH"],
      "app/api/admin/social-project-slots/actions/route.ts": ["POST"],
      "app/api/admin/street-team/route.ts": ["GET"],
      "app/api/admin/subscribers/route.ts": ["GET"],
      "app/api/admin/support/actions/route.ts": ["POST"],
      "app/api/admin/support/route.ts": ["GET"],
      "app/api/admin/test-access/route.ts": ["GET", "PATCH", "POST"],
      "app/api/admin/token-launches/route.ts": ["GET"],
      "app/api/client-errors/route.ts": ["POST"],
      "app/api/cron/outreach/route.ts": ["GET"],
      "app/api/cron/social-posting/route.ts": ["GET"],
      "app/api/cron/subscription-lifecycle/route.ts": ["GET"],
      "app/api/dexscreener-pair/route.ts": ["GET"],
      "app/api/generate-free-site/route.ts": ["POST"],
      "app/api/generate-site-page/challenge/route.ts": ["POST"],
      "app/api/generate-site-page/route.ts": ["POST"],
      "app/api/generate-site-style/route.ts": ["POST"],
      "app/api/generation-status/route.ts": ["GET"],
      "app/api/health/route.ts": ["GET"],
      "app/api/hoodchat/challenge/route.ts": ["POST"],
      "app/api/hoodchat/messages/route.ts": ["GET", "POST"],
      "app/api/hoodchat/report/route.ts": ["POST"],
      "app/api/plan-payments/preflight/route.ts": ["POST"],
      "app/api/plan-payments/quote/route.ts": ["GET"],
      "app/api/plan-payments/verify/route.ts": ["POST"],
      "app/api/publish/challenge/route.ts": ["POST"],
      "app/api/publish/route.ts": ["POST"],
      "app/api/publish/visibility/route.ts": ["POST"],
      "app/api/social/challenge/route.ts": ["POST"],
      "app/api/social/connections/route.ts": ["GET"],
      "app/api/social/draft/route.ts": ["POST"],
      "app/api/social/mascot/image/route.ts": ["GET", "POST"],
      "app/api/social/mascot/visual-dna/route.ts": ["POST"],
      "app/api/social/posts/cancel/route.ts": ["POST"],
      "app/api/social/posts/reschedule/route.ts": ["POST"],
      "app/api/social/posts/route.ts": ["GET", "POST"],
      "app/api/social/project-slots/release/route.ts": ["POST"],
      "app/api/social/project-slots/route.ts": ["GET"],
      "app/api/social/telegram/connect/route.ts": ["POST"],
      "app/api/social/telegram/disconnect/route.ts": ["POST"],
      "app/api/social/telegram/route.ts": ["POST"],
      "app/api/social/telegram/status/route.ts": ["GET"],
      "app/api/social/voice-profile/route.ts": ["POST"],
      "app/api/social/voice-sample/route.ts": ["POST"],
      "app/api/social/x/connect/callback/route.ts": ["GET"],
      "app/api/social/x/connect/start/route.ts": ["POST"],
      "app/api/social/x/disconnect/route.ts": ["POST"],
      "app/api/street-team/interest/route.ts": ["GET", "POST"],
      "app/api/subscriptions/status/route.ts": ["GET"],
      "app/api/support/challenge/route.ts": ["POST"],
      "app/api/support/tickets/[id]/close/route.ts": ["POST"],
      "app/api/support/tickets/[id]/reply/route.ts": ["POST"],
      "app/api/support/tickets/anonymous/route.ts": ["POST"],
      "app/api/support/tickets/reference/route.ts": ["GET"],
      "app/api/support/tickets/route.ts": ["GET", "POST"],
      "app/api/telegram/subscription-webhook/route.ts": ["POST"],
      "app/api/token-chat/challenge/route.ts": ["POST"],
      "app/api/token-chat/messages/route.ts": ["GET", "POST"],
      "app/api/token-chat/report/route.ts": ["POST"],
      "app/api/token-holder-stats/route.ts": ["GET"],
      "app/api/token-launches/challenge/route.ts": ["POST"],
      "app/api/token-launches/route.ts": ["GET", "POST"],
      "app/api/token-trades/route.ts": ["GET"],
      "app/api/trending-robinhood/route.ts": ["GET"],
    });
  });

  it("lists every extracted server module covered by the suite", async () => {
    const serverFiles = (await walk(path.join(ROOT, "lib", "server")))
      .filter((file) => file.endsWith(".ts"))
      .map(relative)
      .sort();

    expect(serverFiles).toEqual([
      "lib/server/admin-accounts.ts",
      "lib/server/admin-auth.ts",
      "lib/server/admin-operations-costs.ts",
      "lib/server/admin-operations-store.ts",
      "lib/server/admin-operations.ts",
      "lib/server/admin-session-store.ts",
      "lib/server/ai-operation-cost-store.ts",
      "lib/server/ai-pricing.ts",
      "lib/server/ai-responses-runtime.ts",
      "lib/server/ai-usage.ts",
      "lib/server/api-protection.ts",
      "lib/server/artwork-identity-request.ts",
      "lib/server/bespoke-site-challenge-store.ts",
      "lib/server/bespoke-site-entitlement.ts",
      "lib/server/chat-auth.ts",
      "lib/server/chat-moderation.ts",
      "lib/server/client-errors-store.ts",
      "lib/server/content-filter.ts",
      "lib/server/curve-progress-cache.ts",
      "lib/server/dexscreener.ts",
      "lib/server/fixed-operating-costs-store.ts",
      "lib/server/generate-site-page-stream.ts",
      "lib/server/generate-site-style.ts",
      "lib/server/hoodchat-store.ts",
      "lib/server/mascot-image-request.ts",
      "lib/server/mascot-image-usage-store.ts",
      "lib/server/mascot-prompt-builder.ts",
      "lib/server/mascot-visual-dna-pipeline.ts",
      "lib/server/outreach-approve.ts",
      "lib/server/outreach-cron.ts",
      "lib/server/outreach-store.ts",
      "lib/server/outreach-templates.ts",
      "lib/server/outreach-x-client.ts",
      "lib/server/page-content-sanitise.ts",
      "lib/server/page-content-store.ts",
      "lib/server/page-content.ts",
      "lib/server/plan-payment-config.ts",
      "lib/server/plan-payment-origin.ts",
      "lib/server/plan-payment-proof.ts",
      "lib/server/plan-payments.ts",
      "lib/server/postgres-publish-store.ts",
      "lib/server/postgres.ts",
      "lib/server/public-generated-sites.ts",
      "lib/server/public-site-artwork.ts",
      "lib/server/public-site-subdomain.ts",
      "lib/server/publish-auth.ts",
      "lib/server/publish-store.ts",
      "lib/server/published-site-validation.ts",
      "lib/server/pumpfun-graduating.ts",
      "lib/server/robinhood-trending.ts",
      "lib/server/sanitise-provider-detail.ts",
      "lib/server/service-isolation.ts",
      "lib/server/social-connections-store.ts",
      "lib/server/social-credentials-crypto.ts",
      "lib/server/social-draft-pipeline.ts",
      "lib/server/social-link-detection.ts",
      "lib/server/social-post-duplicate-detection.ts",
      "lib/server/social-posting-cron.ts",
      "lib/server/social-project-slot-entitlement.ts",
      "lib/server/social-project-slots-store.ts",
      "lib/server/social-reinforcement.ts",
      "lib/server/social-scheduled-posts-store.ts",
      "lib/server/social-studio-action-auth.ts",
      "lib/server/social-studio-entitlement.ts",
      "lib/server/social-telegram-connect.ts",
      "lib/server/social-voice-profile-pipeline.ts",
      "lib/server/social-voice-sample-pipeline.ts",
      "lib/server/social-x-client.ts",
      "lib/server/social-x-cost-store.ts",
      "lib/server/street-team-interest-store.ts",
      "lib/server/subscribers.ts",
      "lib/server/subscription-lifecycle-pipeline.ts",
      "lib/server/subscription-lifecycle.ts",
      "lib/server/subscription-telegram.ts",
      "lib/server/support-ticket-alert.ts",
      "lib/server/support-ticket-attachment.ts",
      "lib/server/support-ticket-auth.ts",
      "lib/server/support-ticket-diagnostics.ts",
      "lib/server/support-tickets-store.ts",
      "lib/server/system-health-pipeline.ts",
      "lib/server/system-health.ts",
      "lib/server/telegram.ts",
      "lib/server/test-access.ts",
      "lib/server/token-chat-creator.ts",
      "lib/server/token-chat-store.ts",
      "lib/server/token-holder-stats.ts",
      "lib/server/token-holders.ts",
      "lib/server/token-launch-artwork-validation.ts",
      "lib/server/token-launch-auth.ts",
      "lib/server/token-launch-curve-lookup.ts",
      "lib/server/token-launch-reconciliation.ts",
      "lib/server/token-launches-store.ts",
      "lib/server/token-market-stats.ts",
      "lib/server/token-trades-rpc.ts",
      "lib/server/x-oauth1-signing.ts",
      "lib/server/x-tweets-client.ts",
    ]);
  });
});
