/* eslint-disable @next/next/no-img-element */
"use client";

import { useEffect, useRef, useState, type TouchEvent } from "react";
import {
  SOCIAL_SHOWCASE_AUTO_ADVANCE_MS,
  SOCIAL_SHOWCASE_CTA_LABEL,
  SOCIAL_SHOWCASE_MASCOT_SCENES,
  SOCIAL_SHOWCASE_SLIDES,
  clampShowcaseIndex,
  nextShowcaseIndex,
  swipeDeltaToStep,
} from "@/lib/social-showcase";
import { requestWorkspaceOpen } from "@/lib/workspace-open-request";
import styles from "./hoodlums-social-showcase.module.css";

function MascotSlot({ label, src }: { label: string; src: string }) {
  const [failed, setFailed] = useState(false);

  return (
    <div className={styles.mascotSlot}>
      {failed ? (
        <div className={styles.mascotPlaceholder} aria-hidden="true">
          <svg viewBox="0 0 24 24" width="26" height="26">
            <path d="M4 5.5A1.5 1.5 0 0 1 5.5 4h13A1.5 1.5 0 0 1 20 5.5v13a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5Zm2.2 12.3 4-5 3 3.2 2.6-3.6 4 5.4M9 9.6a1.6 1.6 0 1 1-3.2 0 1.6 1.6 0 0 1 3.2 0Z" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round" />
          </svg>
        </div>
      ) : (
        <img
          src={src}
          alt={`${label} mascot scene`}
          className={styles.mascotImage}
          loading="lazy"
          onError={() => setFailed(true)}
        />
      )}
      <span className={styles.mascotLabel}>{label}</span>
    </div>
  );
}

function VoiceSlideVisual() {
  return (
    <div className={styles.postCard}>
      <div className={styles.postHeader}>
        <span className={styles.postAvatar} aria-hidden="true">
          AC
        </span>
        <div className={styles.postAuthor}>
          <b>Alley Cat</b>
          <span>@alleycat_eth</span>
        </div>
      </div>
      <p className={styles.postText}>
        woke up, checked the chart, went back to sleep. 340 of you did not. respect. $ALLEY
      </p>
      <div className={styles.postStats}>
        <span>♡ 214</span>
        <span>↻ 63</span>
        <span>💬 28</span>
      </div>
      <span className={styles.generatedBadge}>
        <span className={styles.generatedDot} aria-hidden="true" />
        Generated by your AI · 9:00 AM while you slept
      </span>
    </div>
  );
}

function MascotSlideVisual() {
  return (
    <div className={styles.mascotGrid}>
      {SOCIAL_SHOWCASE_MASCOT_SCENES.map((scene) => (
        <MascotSlot key={scene.label} label={scene.label} src={scene.src} />
      ))}
    </div>
  );
}

function ControlSlideVisual() {
  return (
    <div className={styles.controlCard}>
      <div className={styles.controlToolbar}>
        <div className={styles.modeToggle}>
          <span>AUTOPILOT</span>
          <span className={styles.modeActive}>APPROVE FIRST</span>
        </div>
        <span className={styles.quotaPill}>
          <b>3/5</b> posts · <b>1/2</b> AI images
        </span>
      </div>
      <div className={styles.pendingPost}>
        <div className={styles.pendingMeta}>
          <span>TODAY · 18:00</span>
          <span className={styles.pendingDivider} aria-hidden="true" />
          <span>X + TELEGRAM</span>
        </div>
        <p>340 wallets and not one of you has sold. genuinely moved. $ALLEY</p>
        <div className={styles.pendingActions}>
          <span className={styles.approveButton}>Approve</span>
          <span className={styles.editButton}>Edit</span>
        </div>
      </div>
    </div>
  );
}

const SLIDE_VISUALS: Record<(typeof SOCIAL_SHOWCASE_SLIDES)[number]["id"], () => React.JSX.Element> = {
  voice: VoiceSlideVisual,
  mascot: MascotSlideVisual,
  control: ControlSlideVisual,
};

export function HoodlumsSocialShowcase() {
  const [activeIndex, setActiveIndex] = useState(0);
  const touchStartX = useRef<number | null>(null);
  const total = SOCIAL_SHOWCASE_SLIDES.length;

  useEffect(() => {
    if (typeof window === "undefined") return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    const timer = window.setInterval(() => {
      setActiveIndex((current) => nextShowcaseIndex(current, total));
    }, SOCIAL_SHOWCASE_AUTO_ADVANCE_MS);

    return () => window.clearInterval(timer);
  }, [total, activeIndex]);

  function goToSlide(index: number) {
    setActiveIndex(clampShowcaseIndex(index, total));
  }

  function handleTouchStart(event: TouchEvent<HTMLDivElement>) {
    touchStartX.current = event.touches[0]?.clientX ?? null;
  }

  function handleTouchEnd(event: TouchEvent<HTMLDivElement>) {
    const startX = touchStartX.current;
    touchStartX.current = null;
    if (startX === null) return;

    const endX = event.changedTouches[0]?.clientX ?? startX;
    const step = swipeDeltaToStep(endX - startX);
    if (step !== 0) goToSlide(activeIndex + step);
  }

  function handleCtaClick() {
    requestWorkspaceOpen("new", "pro");
  }

  const slide = SOCIAL_SHOWCASE_SLIDES[activeIndex];
  const SlideVisual = SLIDE_VISUALS[slide.id];

  return (
    <section
      id="social-studio-showcase"
      className={styles.section}
      aria-labelledby="social-showcase-title"
    >
      <div className={styles.glow} aria-hidden="true" />
      <div className={styles.inner}>
        <header className={styles.heading}>
          <span className={styles.eyebrow}>Hoodlums Pro · AI Social Studio</span>
          <h2 id="social-showcase-title">Your token&apos;s marketing, running while you sleep.</h2>
        </header>

        <div
          className={styles.carousel}
          onTouchStart={handleTouchStart}
          onTouchEnd={handleTouchEnd}
        >
          <article key={slide.id} className={styles.slide}>
            <span className={styles.step}>{slide.step}</span>
            <h3 className={styles.title}>{slide.title}</h3>
            <div className={styles.visual}>
              <SlideVisual />
            </div>
            <p className={styles.body}>{slide.body}</p>
            <div className={styles.actions}>
              <button type="button" className={styles.cta} onClick={handleCtaClick}>
                {SOCIAL_SHOWCASE_CTA_LABEL}
              </button>
              <div className={styles.dots} role="tablist" aria-label="Showcase slides">
                {SOCIAL_SHOWCASE_SLIDES.map((dotSlide, dotIndex) => (
                  <button
                    key={dotSlide.id}
                    type="button"
                    role="tab"
                    aria-selected={dotIndex === activeIndex}
                    aria-label={`Show slide ${dotIndex + 1}: ${dotSlide.title}`}
                    className={dotIndex === activeIndex ? styles.dotActive : styles.dot}
                    onClick={() => goToSlide(dotIndex)}
                  />
                ))}
              </div>
            </div>
          </article>
        </div>
      </div>
    </section>
  );
}
